### ISSUE TITLE
Extension not working on Ubuntu 20.04.03

### ISSUE THREAD

**Issue by Johann-Tree** [Martinique/indicator-gnote#1]
I've downloaded and started indicator-gnote as described but I see no indicator. 
I'm on Ubuntu 20.04.3 with Gnome version 3.36.8.
gir1.2-appindicator3-0.1 is installed.

**Comment by Johann-Tree** [comment]
After installing https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ or rather https://extensions.gnome.org/extension/1287/unite/ and several restarts the gnote indicator is displayed and working as expected. Thanks for your work!

**Comment by Martinique** [comment]
> After installing https://extensions.gnome.org/extension/2890/tray-icons-reloaded/ or rather https://extensions.gnome.org/extension/1287/unite/ and several restarts the gnote indicator is displayed and working as expected. Thanks for your work!

Recent GNOME versions have become troublesome for indicator apps, even the modified version in Ubuntu. The best way to work around it seems to be using an extension to restore their functionality, like you did.
